name: Run examples

on:
  push:
     branches:
       - main
  pull_request:
     branches:
       - main

  workflow_dispatch:

jobs:
  examples:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run notebook examples
        run: |
          pip install .[testing,examples]
          pytest --nbmake --nbmake-timeout=3000 examples/